<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/08/02 09:00:07

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=orangehrm_mysql',
  'username' => 'root',
  'password' => 'mysqladmin',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
